Repository w3c/epubcheck, pull requests merged in 2019-02, with the labels that each got.

#971 Change css position warnings to usage messages
  src/main/java/com/adobe/epubcheck/ctc/css/EpubCSSCheckCSSHandler.java
  src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java
  src/main/java/com/adobe/epubcheck/messages/MessageId.java
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_de.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_es.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_fr.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_it.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_ja.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_ko_KR.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_nl.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_pt_BR.properties
  src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
  src/test/resources/com/adobe/epubcheck/test/command_line/failonwarnings/OPS/style_tag_css.xhtml
  src/test/resources/com/adobe/epubcheck/test/command_line/failonwarnings_expected_results.json
  src/test/resources/com/adobe/epubcheck/test/command_line/listSeverities_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/command_line/severity/OPS/style_tag_css.xhtml
  src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadId_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadMessage_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadSeverity_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideMissingFile_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideOk_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/command_line/severity_usage_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/command_line/severity_warning_expected_results.txt
  src/test/resources/com/adobe/epubcheck/test/css/discouraged_expected_results.json
  src/test/resources/com/adobe/epubcheck/test/css/discouraged_expected_results.xml
Labels: status: in discussion

#972 Allow font/* as blessed media types
  src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java
  src/test/resources/30/single/opf/valid/cmt.opf
Labels: status: ready to merge

#928 Add the Compression element
  src/main/resources/com/adobe/epubcheck/schema/30/ocf-encryption-30.rnc
  src/test/java/com/adobe/epubcheck/ocf/OCFCheckerTest.java
  src/test/resources/30/expanded/invalid/ocf-compression/EPUB/content_001.xhtml
  src/test/resources/30/expanded/invalid/ocf-compression/EPUB/nav.xhtml
  src/test/resources/30/expanded/invalid/ocf-compression/EPUB/package.opf
  src/test/resources/30/expanded/invalid/ocf-compression/META-INF/container.xml
  src/test/resources/30/expanded/invalid/ocf-compression/META-INF/encryption.xml
  src/test/resources/30/expanded/invalid/ocf-compression/mimetype
  src/test/resources/30/expanded/valid/ocf-compression/EPUB/content_001.xhtml
  src/test/resources/30/expanded/valid/ocf-compression/EPUB/nav.xhtml
  src/test/resources/30/expanded/valid/ocf-compression/EPUB/package.opf
  src/test/resources/30/expanded/valid/ocf-compression/META-INF/container.xml
  src/test/resources/30/expanded/valid/ocf-compression/META-INF/encryption.xml
  src/test/resources/30/expanded/valid/ocf-compression/mimetype
Labels: spec: EPUB 3.2, status: ready to merge

#979 feat: add new MO-only `aside` epub:type value
  src/main/java/com/adobe/epubcheck/vocab/StructureVocab.java
  src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
  src/test/java/com/adobe/epubcheck/overlay/OverlayCheckerTest.java
  src/test/resources/30/single/overlays/valid/epubtype-aside.smil
  src/test/resources/30/single/xhtml/invalid/epubtype-disallowed.xhtml
Labels: status: ready to merge

#983 Support global ARIA attributes in SVG
  src/main/resources/com/adobe/epubcheck/schema/30/mod/epub-svg11.rnc
  src/main/resources/com/adobe/epubcheck/schema/30/mod/epub-xhtml-svg11.rnc
  src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
  src/test/resources/30/single/svg/valid/aria-attributes.svg
Labels: status: ready to merge
