Repository w3c/epubcheck, pull requests merged in 2019-01, with the labels that each got.

#937 feat: allow missing `alttext` or `annotation-xml` on MathML
  src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java
  src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
  src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
  src/test/resources/30/expanded/invalid/lorem-mathml-noalt/EPUB/wasteland-content.xhtml
  src/test/resources/30/expanded/invalid/lorem-mathml-noalt/EPUB/wasteland-cover.jpg
  src/test/resources/30/expanded/invalid/lorem-mathml-noalt/EPUB/wasteland-nav.xhtml
  src/test/resources/30/expanded/invalid/lorem-mathml-noalt/EPUB/wasteland.css
  src/test/resources/30/expanded/invalid/lorem-mathml-noalt/EPUB/wasteland.opf
  src/test/resources/30/expanded/invalid/lorem-mathml-noalt/META-INF/container.xml
  src/test/resources/30/expanded/invalid/lorem-mathml-noalt/mimetype
  src/test/resources/30/single/xhtml/valid/mathml-noalt.xhtml
Labels: status: in progress

#938 feat: deprecate epub:trigger and epub:switch
  src/main/resources/com/adobe/epubcheck/schema/30/epub-xhtml-30.sch
  src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
  src/test/java/com/adobe/epubcheck/ocf/OCFCheckerTest.java
  src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
  src/test/resources/30/expanded/invalid/lorem-basic-switch/EPUB/wasteland-content.xhtml
  src/test/resources/30/expanded/invalid/lorem-basic-switch/EPUB/wasteland-cover.jpg
  src/test/resources/30/expanded/invalid/lorem-basic-switch/EPUB/wasteland-nav.xhtml
  src/test/resources/30/expanded/invalid/lorem-basic-switch/EPUB/wasteland.css
  src/test/resources/30/expanded/invalid/lorem-basic-switch/EPUB/wasteland.opf
  src/test/resources/30/expanded/invalid/lorem-basic-switch/META-INF/container.xml
  src/test/resources/30/expanded/invalid/lorem-basic-switch/mimetype
  src/test/resources/30/expanded/invalid/switch-missing-property/META-INF/container.xml
  src/test/resources/30/expanded/invalid/switch-missing-property/OPS/content_001.xhtml
  src/test/resources/30/expanded/invalid/switch-missing-property/OPS/nav.xhtml
  src/test/resources/30/expanded/invalid/switch-missing-property/OPS/package.opf
  src/test/resources/30/expanded/invalid/switch-missing-property/mimetype
  src/test/resources/30/expanded/valid/cc-shared-culture.txt
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/audio/asharedculture_soundtrack.mp3
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/captions/cc-en.vtt
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/captions/cc-en.xml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/captions/cc-fr.vtt
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/captions/cc-fr.xml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/css/shared-culture.css
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/fonts/Quicksand_Bold_Oblique.otf
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/fonts/Quicksand_Light.otf
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/images/2565514353_2ae2073e14.jpg
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/images/326261902_3fa36f548d.jpg
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/package.opf
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/script/shared.js
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/cover.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/p10.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/p20.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/p30.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/p40.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/p50.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/p60.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/EPUB/xhtml/toc.xhtml
  src/test/resources/30/expanded/valid/cc-shared-culture/META-INF/container.xml
  src/test/resources/30/expanded/valid/cc-shared-culture/mimetype
  src/test/resources/30/expanded/valid/lorem-basic-switch.txt
  src/test/resources/30/expanded/valid/lorem-basic-switch/EPUB/wasteland-content.xhtml
  src/test/resources/30/expanded/valid/lorem-basic-switch/EPUB/wasteland-cover.jpg
  src/test/resources/30/expanded/valid/lorem-basic-switch/EPUB/wasteland-nav.xhtml
  src/test/resources/30/expanded/valid/lorem-basic-switch/EPUB/wasteland.css
  src/test/resources/30/expanded/valid/lorem-basic-switch/EPUB/wasteland.opf
  src/test/resources/30/expanded/valid/lorem-basic-switch/META-INF/container.xml
  src/test/resources/30/expanded/valid/lorem-basic-switch/mimetype
  src/test/resources/30/single/xhtml/invalid/switch-001.xhtml
  src/test/resources/30/single/xhtml/invalid/switch-default-before-case.xhtml
  src/test/resources/30/single/xhtml/invalid/switch-default-twice.xhtml
  src/test/resources/30/single/xhtml/invalid/switch-deprecated.xhtml
  src/test/resources/30/single/xhtml/invalid/switch-no-case.xhtml
  src/test/resources/30/single/xhtml/invalid/switch-no-default.xhtml
  src/test/resources/30/single/xhtml/invalid/switch-no-requirednamespace.xhtml
  src/test/resources/30/single/xhtml/invalid/trigger-badrefs.xhtml
  src/test/resources/30/single/xhtml/invalid/trigger-deprecated.xhtml
  src/test/resources/30/single/xhtml/invalid/trigger.xhtml
  src/test/resources/30/single/xhtml/valid/switch-001.xhtml
  src/test/resources/30/single/xhtml/valid/trigger.xhtml
  src/test/resources/com/adobe/epubcheck/test/opf/Properties_expected_results.json
Labels: status: accepted

#939 test: add a test for empty lists in nav doc
  src/test/java/com/adobe/epubcheck/nav/NavCheckerTest.java
  src/test/resources/30/single/nav/invalid/nav-empty-list.xhtml
Labels: status: accepted

#933 Refactored "run" and "processEpubFile" file methods
  src/main/java/com/adobe/epubcheck/tool/EpubChecker.java
Labels: status: needs review, type: improvement

#918 Some OSGi related changes
  pom.xml
Labels: status: ready to merge, type: maintenance

#930 Suppress warnings from compiler
  src/main/java/com/adobe/epubcheck/util/XmlReportAbstract.java
  src/main/java/com/adobe/epubcheck/vocab/PrefixDeclarationParser.java
Labels: priority: low, status: ready to merge

#944 fix: `switch` item property doesn't apply to `svg:switch`
  src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java
  src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
  src/test/resources/30/expanded/valid/svg-switch/META-INF/container.xml
  src/test/resources/30/expanded/valid/svg-switch/OPS/content_001.xhtml
  src/test/resources/30/expanded/valid/svg-switch/OPS/nav.xhtml
  src/test/resources/30/expanded/valid/svg-switch/OPS/package.opf
  src/test/resources/30/expanded/valid/svg-switch/mimetype
Labels: spec: EPUB 3.x, status: needs review

#949 fix: do not check entity references in comment or CDATA
  src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java
  src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
  src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
  src/test/resources/30/expanded/valid/entities-in-comment-or-cdata/META-INF/container.xml
  src/test/resources/30/expanded/valid/entities-in-comment-or-cdata/OPS/content_001.xhtml
  src/test/resources/30/expanded/valid/entities-in-comment-or-cdata/OPS/nav.xhtml
  src/test/resources/30/expanded/valid/entities-in-comment-or-cdata/OPS/package.opf
  src/test/resources/30/expanded/valid/entities-in-comment-or-cdata/mimetype
  src/test/resources/30/single/xhtml/invalid/entities-missing-semicolon.xhtml
  src/test/resources/30/single/xhtml/invalid/entities-unknown.xhtml
  src/test/resources/30/single/xhtml/valid/entities-internal.xhtml
  src/test/resources/30/single/xhtml/valid/entities.xhtml
  src/test/resources/com/adobe/epubcheck/test/encryption/epub20_encryption_binary_content.epub_expected_results.xml
  src/test/resources/com/adobe/epubcheck/test/xhtml/dtd_expected_results.json
Labels: status: needs review

#955 fix: resolve relative URIs against their base
  src/main/java/com/adobe/epubcheck/css/CSSHandler.java
  src/main/java/com/adobe/epubcheck/ctc/EpubCSSCheck.java
  src/main/java/com/adobe/epubcheck/ctc/EpubExtLinksCheck.java
  src/main/java/com/adobe/epubcheck/ctc/EpubNCXCheck.java
  src/main/java/com/adobe/epubcheck/ctc/EpubNavCheck.java
  src/main/java/com/adobe/epubcheck/ctc/epubpackage/EpubPackage.java
  src/main/java/com/adobe/epubcheck/dict/SearchKeyMapHandler.java
  src/main/java/com/adobe/epubcheck/dtbook/DTBookHandler.java
  src/main/java/com/adobe/epubcheck/ncx/NCXHandler.java
  src/main/java/com/adobe/epubcheck/opf/OPFHandler.java
  src/main/java/com/adobe/epubcheck/opf/OPFHandler30.java
  src/main/java/com/adobe/epubcheck/ops/OPSHandler.java
  src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java
  src/main/java/com/adobe/epubcheck/overlay/OverlayHandler.java
  src/main/java/com/adobe/epubcheck/util/PathUtil.java
  src/test/java/com/adobe/epubcheck/api/Epub20CheckExpandedTest.java
  src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
  src/test/java/com/adobe/epubcheck/test/message_coverage.java
  src/test/java/com/adobe/epubcheck/util/PathUtilTest.java
  src/test/resources/30/expanded/valid/base-uri/META-INF/container.xml
  src/test/resources/30/expanded/valid/base-uri/OPS/css/style.css
  src/test/resources/30/expanded/valid/base-uri/OPS/nav.xhtml
  src/test/resources/30/expanded/valid/base-uri/OPS/package.opf
  src/test/resources/30/expanded/valid/base-uri/OPS/xhtml/content_001.xhtml
  src/test/resources/30/expanded/valid/base-uri/mimetype
  src/test/resources/com/adobe/epubcheck/test/package/interesting_paths_epub3_expected_results.json
  src/test/resources/com/adobe/epubcheck/test/package/interesting_paths_epub3_expected_results.xml
Labels: status: needs review

#914 Localization updates (small changes + new locales ko_KR, pt_BR)
  src/main/assembly/README-dist.txt
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_de.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_es.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_fr.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_it.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_ja.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_ko_KR.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_nl.properties
  src/main/resources/com/adobe/epubcheck/messages/MessageBundle_pt_BR.properties
  src/main/resources/com/adobe/epubcheck/util/messages_de.properties
  src/main/resources/com/adobe/epubcheck/util/messages_es.properties
  src/main/resources/com/adobe/epubcheck/util/messages_fr.properties
  src/main/resources/com/adobe/epubcheck/util/messages_it.properties
  src/main/resources/com/adobe/epubcheck/util/messages_ja.properties
  src/main/resources/com/adobe/epubcheck/util/messages_ko_KR.properties
  src/main/resources/com/adobe/epubcheck/util/messages_nl.properties
  src/main/resources/com/adobe/epubcheck/util/messages_pt_BR.properties
  src/main/resources/com/thaiopensource/datatype/xsd/resources/Messages_it.properties
  src/main/resources/com/thaiopensource/datatype/xsd/resources/Messages_pt_BR.properties
  src/main/resources/com/thaiopensource/relaxng/pattern/resources/Messages_it.properties
  src/main/resources/com/thaiopensource/relaxng/pattern/resources/Messages_ja.properties
  src/main/resources/com/thaiopensource/relaxng/pattern/resources/Messages_ko_KR.properties
  src/main/resources/com/thaiopensource/relaxng/pattern/resources/Messages_pt_BR.properties
  src/main/resources/com/thaiopensource/validate/schematron/resources/Messages_it.properties
  src/main/resources/com/thaiopensource/validate/schematron/resources/Messages_ko_KR.properties
  src/main/resources/com/thaiopensource/validate/schematron/resources/Messages_pt_BR.properties
  src/main/resources/org/idpf/epubcheck/util/css/messages_it.properties
  src/main/resources/org/idpf/epubcheck/util/css/messages_ko_KR.properties
  src/main/resources/org/idpf/epubcheck/util/css/messages_pt_BR.properties
Labels: type: improvement

#947 Re-enable openjdk11 on Travis CI
  .travis.yml
Labels: status: completed, type: maintenance
