Repository w3c/epubcheck, pull requests merged in 2024-12, with the labels that each got.

#1580 chore: run build action on all branches
  .github/workflows/maven-ci.yml
Labels: type: maintenance, status: ready to merge

#1579 fix: rare decoding error on UTF-8 documents
  src/main/java/com/adobe/epubcheck/xml/XMLEncodingSniffer.java
  src/main/java/com/adobe/epubcheck/xml/XMLParser.java
Labels: status: ready to merge

#1581 fix: allow CSS custom properties with no value
  src/main/java/org/idpf/epubcheck/util/css/CssParser.java
  src/test/java/org/idpf/epubcheck/util/css/CssParserTest.java
  src/test/resources/css/custom-properties.css
Labels: status: ready to merge

#1582 fix: NullPointerException was raised on some data URLs
  src/main/java/com/adobe/epubcheck/ocf/OCFContainer.java
  src/main/java/org/w3c/epubcheck/core/references/ReferenceRegistry.java
  src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/EPUB/content_001.xhtml
  src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/EPUB/nav.xhtml
  src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/EPUB/package.opf
  src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/META-INF/container.xml
  src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/mimetype
  src/test/resources/epub3/03-resources/resources.feature
Labels: status: ready to merge

#1584 fix: prevent some internal URLs from leaking in messages
  src/main/java/com/adobe/epubcheck/opf/OPFChecker.java
  src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java
Labels: status: ready to merge

#1586 refactor: remove primitive wrapper constructor
  src/main/java/com/adobe/epubcheck/overlay/ClipTime.java
Labels: status: ready for review

#1588 fix: recognize the `a11y:exemption` property
  src/main/java/com/adobe/epubcheck/vocab/AccessibilityVocab.java
  src/test/resources/epub-accessibility/accessibility.feature
  src/test/resources/epub-accessibility/files/metadata-a11y-exemption-valid.opf
Labels: status: ready for review

#1591 fix: simplify `--failonwarnings` documentation
  src/main/java/com/adobe/epubcheck/tool/EpubChecker.java
  src/main/resources/com/adobe/epubcheck/util/messages.properties
  src/main/resources/com/adobe/epubcheck/util/messages_da.properties
  src/main/resources/com/adobe/epubcheck/util/messages_de.properties
  src/main/resources/com/adobe/epubcheck/util/messages_es.properties
  src/main/resources/com/adobe/epubcheck/util/messages_fr.properties
  src/main/resources/com/adobe/epubcheck/util/messages_it.properties
  src/main/resources/com/adobe/epubcheck/util/messages_ja.properties
  src/main/resources/com/adobe/epubcheck/util/messages_ko_KR.properties
  src/main/resources/com/adobe/epubcheck/util/messages_nl.properties
  src/main/resources/com/adobe/epubcheck/util/messages_pt_BR.properties
  src/main/resources/com/adobe/epubcheck/util/messages_zh_TW.properties
  src/test/resources/cli/cli.feature
Labels: status: ready for review

#1569 chore: bump GitHub Action versions
  .github/workflows/maven-ci.yml
Labels: status: ready for review

#1571 Migrate from `Charsets` to `StandardCharsets`.
  src/main/java/com/adobe/epubcheck/messages/LocalizedMessages.java
  src/main/java/com/adobe/epubcheck/util/Messages.java
Labels: status: ready for review

#1592 chore(deps): bump Jackson from 1.9.12 to 2.18.2
  pom.xml
  src/main/java/com/adobe/epubcheck/api/EPUBLocation.java
  src/main/java/com/adobe/epubcheck/api/MasterReport.java
  src/main/java/com/adobe/epubcheck/reporting/CheckMessage.java
  src/main/java/com/adobe/epubcheck/reporting/CheckerMetadata.java
  src/main/java/com/adobe/epubcheck/reporting/CheckingReport.java
  src/main/java/com/adobe/epubcheck/reporting/ItemMetadata.java
  src/main/java/com/adobe/epubcheck/reporting/PublicationMetadata.java
  src/main/java/com/adobe/epubcheck/util/JsonWriter.java
Labels: status: ready to merge
